Added Mautrix-Whatsapp
felbinger/AdminGuide pull request #86
Opened 2023-05-05 18:07 UTC by AmphoMoronal

2023-05-05 18:43 UTC, felbinger commented
I HATE FUCKING GIT @MarcelCoding

2023-05-05 18:44 UTC, felbinger commented on docs/services/bookstack.md
> +Wenn dies noch gespeichert wurde, ist die Keycloak Konfiguration vollendet.
umformulieren! Wörtliche Übersetzung passt hier nicht.

2023-05-05 18:44 UTC, felbinger commented on docs/services/bookstack.md
> +Bookstack ist ein einfaches Wiki / KnowledgeBase Software.
??

2023-05-05 18:44 UTC, felbinger commented on docs/services/matrix.md
> -        ports:
??

2023-05-05 18:46 UTC, felbinger commented on docs/services/matrix.md
> +jetzt auch eine `registration.yaml`. Diese Datei muss in `/srv/matrix/synapse/` verschoben werden und wenn man vorhat
bitte kopieren, sonst wird beim neustart der bridge eine neue `registration.yaml` erstellt

2023-05-08 08:56 UTC, felbinger requested changes

2023-05-08 08:56 UTC, felbinger commented on docs/services/matrix.md
> +## Mautrix-WhatsApp (WhatsApp Bridge)
change to:
```
### `mautrix-whatsapp` (WhatsApp Bridge)
```

2023-05-08 09:53 UTC, felbinger requested changes

2023-05-08 09:53 UTC, felbinger commented on docs/services/matrix.md
> +    labels:
muss eingerückt sein

2023-05-08 09:53 UTC, felbinger commented on docs/services/matrix.md
> +        - "[::1]:8000:8080"
falsch eingerückt

2023-05-08 09:53 UTC, felbinger commented on docs/services/matrix.md
> +Jetzt befindet sich in dem Ordner `/srv/matrix/mautrix-whatsapp/` eine `config.yaml`. Diese Konfigurationsdatei ist
ersten satz streichen, hinter Konfigurationsdatei (`/srv/matrix/mautrix-whatsapp/config.yaml`), "ausschließlich für die Konfiguration für die WhatsApp Bridge mit dem dazugehörigen Bot" ist unnötig und kann entfernt werden

2023-05-08 09:53 UTC, felbinger commented on docs/services/prometheus.md
kann dann gelöscht werden wenn sie leer ist...

2023-05-08 09:55 UTC, AmphoMoronal commented on docs/services/matrix.md
> +    labels:
Auto formatting und so -_-

2023-05-08 10:04 UTC, felbinger requested changes

2023-05-08 10:04 UTC, felbinger commented on docs/services/bookstack.md
> +```yaml
nope

2023-05-08 10:04 UTC, felbinger commented on docs/services/bookstack.md
> +```yaml
nope

2023-05-08 10:04 UTC, felbinger commented on docs/services/matrix.md
> +        - "traefik.enable=true"
falsch eingerückt, vorher war richtig

2023-05-08 10:04 UTC, felbinger commented on docs/services/matrix.md
> +            - "[::1]:8000:8080"
falsch eingerückt, vorher war richtig

2023-05-08 10:05 UTC, AmphoMoronal commented on docs/services/matrix.md
> +            - "[::1]:8000:8080"
Entscheid dich doch ma 😂

2023-05-08 11:50 UTC, closed without merging